BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "nodejs22"
BBFILE_PATTERN_nodejs22 = "^${LAYERDIR}/"
BBFILE_PRIORITY_nodejs22 = "50"

LAYERDEPENDS_nodejs22 = "core"
LAYERSERIES_COMPAT_nodejs22 = "kirkstone"
